FROM golang:%%GOLANG_VERSION%%-alpine3.13

RUN apk update && apk upgrade \
 && apk add \
    bash \
    git \
    gcc \
    libc-dev \
 && rm -rf /var/cache/apk/* \
 && rm -rf /tmp/* \
 && wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s %%GOLANGCI_VERSION%% \
 && golangci-lint --version

WORKDIR /app

COPY .golangci.yml /

CMD ["/bin/bash"]