FROM golang:%%GOLANG_VERSION%%-alpine

RUN apk update && apk upgrade \
 && apk add \
    bash \
    git \
    gcc \
    libc-dev \
    curl \
 && rm -rf /var/cache/apk/* \
 && rm -rf /tmp/* \
 && curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s %%GOLANGCI_VERSION%% \
 && golangci-lint --version

WORKDIR /app

COPY .golangci.yml /

CMD ["/bin/bash"]