FROM golang:%%GOLANG_VERSION%%-alpine

RUN apk update && apk upgrade \
 && apk add \
    bash \
    curl \
    git \
    gcc \
    libc-dev \
 && rm -rf /var/cache/apk/* \
 && rm -rf /tmp/* \

WORKDIR /app

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- %%GOLANGCI_VERSION%% \
 && curl -sO https://raw.githubusercontent.com/spacetab-io/linter-go/%%GOLANGCI_CONFIG_VERSION%%/.golangci.yml \
 && golangci-lint -v version


CMD ["/bin/bash"]